PersonnelOffice/personneloffice-web/src/main/java/com/coherent/api/dao/entity/PersonCardEntity.java
package com.coherent.api.dao.entity;


import com.coherent.api.controller.jsonSerializer.DateSerializer;
import com.coherent.api.controller.jsonSerializer.EnumSerializer;
import com.coherent.api.dao.enums.education.EducationEnum;
import com.coherent.api.dao.enums.education.LearningFormEnum;
import com.coherent.api.dao.enums.general.*;
import com.coherent.api.util.Constants;
import org.codehaus.jackson.map.annotate.JsonSerialize;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

@Entity(name = "person_card")
public class PersonCardEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "person_card_id")
    private Long id;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "patronymic")
    private String patronymic;

    @Column(name = "card_number")
    private String cardNumber;

    @Column(name = "tab_number")
    private String tabNumber;

    @Column(name = "status")
    @Enumerated(EnumType.STRING)
    @JsonSerialize(using = EnumSerializer.class)
    private StatusEnum status;

    @Column(name = "trade_unionist")
    private Boolean tradeUnionist;

    @Column(name = "nationality")
    @Enumerated(EnumType.STRING)
    @JsonSerialize(using = EnumSerializer.class)
    private NationalityEnum nationality;

    @Column(name = "document")
    private String document;

    @Column(name = "document_series")
    private String documentSeries;

    @Column(name = "document_serial_number")
    private String documentSerialNumber;

    @Column(name = "document_individual_number")
    private String documentIndividualNumber;

    @Column(name = "document_date_issuance")
    @DateTimeFormat(pattern = Constants.DATE_FORMAT)
    @JsonSerialize(using = DateSerializer.class)
    private Date documentDateIssuance;

    @Column(name = "document_validity_period")
    @DateTimeFormat(pattern = Constants.DATE_FORMAT)
    @JsonSerialize(using = DateSerializer.class)
    private Date documentValidityPeriod;

    @Column(name = "document_issued_by")
    private String documentIssuedBy;

    @Column(name = "latin")
    private String latin;

    @Column(name = "insurance_certificate_number")
    private String insuranceCertificateNumber;

    @Column(name = "birthday")
    @DateTimeFormat(pattern = Constants.DATE_FORMAT)
    @JsonSerialize(using = DateSerializer.class)
    private Date birthday;

    @Column(name = "allocation")
    private String allocation;

    @Column(name = "birthplace_country")
    @Enumerated(EnumType.STRING)
    @JsonSerialize(using = EnumSerializer.class)
    private CountryEnum birthplaceCountry;

    @Column(name = "birthplace_province")
    private String birthplaceProvince;

    @Column(name = "birthplace_region")
    private String birthplaceRegion;

    @Column(name = "birthplace_locality")
    private String birthplaceLocality;

    @Column(name = "large_family")
    private String largeFamily;

    @Column(name = "gender")
    @Enumerated(EnumType.STRING)
    @JsonSerialize(using = EnumSerializer.class)
    private GenderEnum gender;

    @Column(name = "family_status")
    @Enumerated(EnumType.STRING)
    @JsonSerialize(using = EnumSerializer.class)
    private FamilyStatusEnum familyStatus;

    @Column(name = "learning_form")
    @Enumerated(EnumType.STRING)
    @JsonSerialize(using = EnumSerializer.class)
    private LearningFormEnum learningForm;

    @Column(name = "education_degree")
    @Enumerated(EnumType.STRING)
    @JsonSerialize(using = EnumSerializer.class)
    private EducationEnum educationDegree;

    @Column(name = "institution")
    private String institution;

    @Column(name = "studying")
    private Boolean studying;

    @Column(name = "budget")
    private Boolean budget;

    @Column(name = "test_period")
    private Boolean testPeriod;

    @Column(name = "test_period_end_date")
    @DateTimeFormat(pattern = Constants.DATE_FORMAT)
    @JsonSerialize(using = DateSerializer.class)
    private Date testPeriodEndDate;

    @Column(name = "studying_end_date")
    @DateTimeFormat(pattern = Constants.DATE_FORMAT)
    @JsonSerialize(using = DateSerializer.class)
    private Date studyingEndDate;

    @Column(name = "allocation_start_date")
    @DateTimeFormat(pattern = Constants.DATE_FORMAT)
    @JsonSerialize(using = DateSerializer.class)
    private Date allocationStartDate;

    @Column(name = "allocation_end_date")
    @DateTimeFormat(pattern = Constants.DATE_FORMAT)
    @JsonSerialize(using = DateSerializer.class)
    private Date allocationEndDate;

    @Column(name = "certificate_number")
    private String certificateNumber;

    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.EAGER)
    @JoinColumn( name = "registration_address_id", referencedColumnName = "address_id", updatable = true, insertable = true)
    @Fetch(FetchMode.SELECT)
    private AddressEntity registrationAddress = new AddressEntity();

    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.EAGER)
    @JoinColumn( name = "residential_address_id", referencedColumnName = "address_id", updatable = true, insertable = true)
    @Fetch(FetchMode.SELECT)
    private AddressEntity residentialAddress = new AddressEntity();

    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.EAGER)
    @JoinColumn( name = "reservist_id", referencedColumnName = "military_id", updatable = true, insertable = true)
    @Fetch(FetchMode.SELECT)
    private MilitaryEntity reservist = new MilitaryEntity();

    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch = FetchType.EAGER)
    @JoinColumn( name = "conscript_id", referencedColumnName = "military_id", updatable = true, insertable = true)
    @Fetch(FetchMode.SELECT)
    private MilitaryEntity conscript = new MilitaryEntity();

    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinColumn(name = "person_card_id", referencedColumnName = "person_card_id", updatable = false, insertable = true)
    @Fetch(FetchMode.SELECT)
    private List<FamilyMemberEntity> familyMembers;

    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinColumn(name = "person_card_id", referencedColumnName = "person_card_id", updatable = false, insertable = true)
    @Fetch(FetchMode.SELECT)
    private List<EducationEntity> education;

    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinColumn(name = "person_card_id", referencedColumnName = "person_card_id", updatable = false, insertable = true)
    @Fetch(FetchMode.SELECT)
    private List<TrainingEntity> training;

    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinColumn(name = "person_card_id", referencedColumnName = "person_card_id", updatable = false, insertable = true)
    @Fetch(FetchMode.SELECT)
    private List<RetrainingEntity> retraining;


    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinColumn(name = "person_card_id", referencedColumnName = "person_card_id", updatable = false, insertable = true)
    @Fetch(FetchMode.SELECT)
    private List<AdditionalInfoEntity> additionals;

    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinColumn(name = "person_card_id", referencedColumnName = "person_card_id", updatable = false, insertable = true)
    @Fetch(FetchMode.SELECT)
    private List<AssignmentEntity> assignments;

    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinColumn(name = "person_card_id", referencedColumnName = "person_card_id", updatable = false, insertable = true)
    @Fetch(FetchMode.SELECT)
    private List<ContractEntity> contracts;

    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinColumn(name = "person_card_id", referencedColumnName = "person_card_id", updatable = false, insertable = true)
    @Fetch(FetchMode.SELECT)
    private List<AttestationEntity> attestations;

    @OneToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinColumn(name = "person_card_id", referencedColumnName = "person_card_id", updatable = false, insertable = true)
    @Fetch(FetchMode.SELECT)
    private List<VacationEntity> vacations;

    @ManyToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinTable(
            name="card_document_xref",
            joinColumns={@JoinColumn(name="person_card_id", referencedColumnName="person_card_id")},
            inverseJoinColumns={@JoinColumn(name="document_id", referencedColumnName="document_id")})
    @Fetch(FetchMode.SELECT)
    private List<DocumentEntity> documents;

    public PersonCardEntity(){
        registrationAddress = null;
        residentialAddress = null;
        reservist = null;
        conscript = null;
    }

    public List<VacationEntity> getVacations() {
        return vacations;
    }

    public void setVacations(List<VacationEntity> vacation) {
        this.vacations = vacation;
    }

    public String getShortName(){
        return lastName + " " + firstName.charAt(0) + ". " + patronymic.charAt(0) + ".";
    }

    public AssignmentEntity getLastAssignment(){
        if(assignments!= null && !assignments.isEmpty()){
            return assignments.get(assignments.size()-1);
        }
        return null;
    }

    public String getFamilyMembersAsString(){
        SimpleDateFormat sdf = new SimpleDateFormat(Constants.DATE_FORMAT);
        StringBuilder sb = new StringBuilder();
        String prefix = "";
        for(FamilyMemberEntity entity: familyMembers){
            sb.append(prefix);
            prefix = ", ";

PersonnelOffice/personneloffice-web/src/main/webapp/WEB-INF/pages/person/dialogs/additional_information.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<div class="button-block ${not empty personCard.id ? '' : 'disabled-crud-icons' }">
    <a class="add-row crud" href="#" data-url="additional_info" data-person-id="${not empty personCard.id ? personCard.id : 0 }" data-id="0"></a>
    <a class="edit-row crud" href="#" data-person-id="${personCard.id}"></a>
    <a class="delete-row crud" href="#"></a>
</div>

<span class="table-name">Дополнительные сведения</span>

<div class="info-tables-wrapper">

    <table id="additional_info" class="info-tables">
        <thead data-entity-attributes="data-id:id">
        <tr>
            <td data-entity-property="eventName">Событие</td>
            <td data-entity-property="eventDate">Дата события</td>
            <td data-entity-property="notificationDate">Дата уведомления</td>
        </tr>
        </thead>
        <tbody>
        <c:forEach items="${personCard.additionals}" var="additionalInfo">
            <tr data-url="additional_info" data-person-id="${personCard.id}" data-id="${additionalInfo.id}">
                <td>${additionalInfo.eventName}</td>
                <td><spring:eval expression="additionalInfo.eventDate"/></td>
                <td><spring:eval expression="additionalInfo.notificationDate"/></td>
            </tr>
        </c:forEach>
        </tbody>
    </table>

</div>

PersonnelOffice/personneloffice-web/src/main/webapp/WEB-INF/pages/person/dialogs/assignment_information.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>

    <div class="button-block ${not empty personCard.id ? '' : 'disabled-crud-icons' }">
        <a href="#" class="add-row crud" data-url="assignment" data-person-id="${not empty personCard.id ? personCard.id : 0 }" data-id="0"></a>
        <a href="#" class="edit-row crud"></a>
        <a href="#" class="delete-row crud"></a>
    </div>
    <span class="table-name">Назначения/Перемещения</span>

<div class="info-tables-wrapper">

    <table id="assignment_table" class="info-tables">
        <thead data-entity-attributes="data-id:id">
            <tr>
                <td data-entity-property="position" class="assignment-head-td">Должность</td>
                <td data-entity-property="rate" class="assignment-head-td">Кол-во ставок</td>
                <td data-entity-property="form" class="assignment-head-td">Форма</td>
                <td data-entity-property="contractNumber" class="assignment-head-td">№ котракта/ договора</td>
                <td data-entity-property="contractDate" class="assignment-head-td">Дата контракта/ договора</td>
                <td data-entity-property="contractStart" class="assignment-head-td">Дата начала контракта/ договора</td>
                <td data-entity-property="contractEnd" class="assignment-head-td">Дата окончания контракта/ договора</td>
                <td data-entity-property="orderNumber" class="assignment-head-td">№ приказа</td>
                <td data-entity-property="orderDate" class="assignment-head-td">Дата приказа</td>
                <td data-entity-property="department" class="assignment-head-td">Подразделение (отдел)</td>
            </tr>
        </thead>
        <tbody>
            <c:forEach var="assignment" items="${personCard.assignments}">
                <tr data-url="assignment" data-person-id="${personCard.id}" data-id="${assignment.id}">
                    <td>
                        <c:if test="${assignment.position != null}">
                            <spring:message code="${assignment.position.value}"/>
                        </c:if>
                    </td>
                    <td>${assignment.rate}</td>
                    <td>
                        <c:if test="${assignment.form != null}">
                            <spring:message code="${assignment.form.value}"/>
                        </c:if>
                    </td>
                    <td>${assignment.contractNumber}</td>
                    <td><f:formatDate value="${assignment.contractDate}" pattern="dd.MM.yyyy"/></td>
                    <td><f:formatDate value="${assignment.contractStart}" pattern="dd.MM.yyyy"/></td>
                    <td><f:formatDate value="${assignment.contractEnd}" pattern="dd.MM.yyyy"/></td>
                    <td>${assignment.orderNumber}</td>
                    <td><f:formatDate value="${assignment.orderDate}" pattern="dd.MM.yyyy"/></td>
                    <td>${assignment.department}</td>
                </tr>
            </c:forEach>
        </tbody>
    </table>
</div>

<hr>
<span class="table-name">Увольнения</span>

<div class="info-tables-wrapper">

    <table id="dismissal_table" data-person-id="${personCard.id}" class="info-tables">

        <thead>
        <tr>
            <td data-entity-property="paperNumber">№ приказа</td>
            <td data-entity-property="paperDate">Дата приказа</td>
            <td data-entity-property="reason">Основание</td>
            <td data-entity-property="dismissalDate">Дата увольнения</td>
            <td data-entity-property="compensationDays">Кол-во компенс. дней</td>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

PersonnelOffice/personneloffice-web/src/main/webapp/WEB-INF/pages/person/dialogs/card_editor.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="com.coherent.api.dao.enums.general.*" %>
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<c:set var="formID" value="generalInformationForm" scope="request"/>
<% pageContext.setAttribute("genders", GenderEnum.values()); %>
<% pageContext.setAttribute("familyStatuses", FamilyStatusEnum.values()); %>
<% pageContext.setAttribute("academicRanks", AcademicRankEnum.values()); %>
<% pageContext.setAttribute("statuses", StatusEnum.values()); %>
<% pageContext.setAttribute("documents", DocumentTypeEnum.values()); %>


<tiles:insertDefinition name="dialogTemplate">
    <tiles:putAttribute name="body">
        <form:form id="generalInformationForm" action="${pageContext.request.contextPath}/persons/save" commandName="personCard" >
            <form:hidden path="id" id="parent_id" value="${not empty personCard.id ? personCard.id : 0 }" />
            <div id="head">
                <div class="avatar">
                    <span class="ava_img"></span>
                    <a class="update_photo" href="#" title="Обновить фото"></a>
                </div>
                <div class="info_block">
                    <table>
                        <tr>
                            <td>Фамилия<i class="red">*</i></td>
                            <td><form:input path="lastName" class="required"/></td>
                            <td><a class="old_lastName" href="#"></a></td>
                        </tr>
                        <tr>
                            <td>Имя<i class="red">*</i></td>
                            <td><form:input path="firstName" class="required"/></td>
                        </tr>
                        <tr>
                            <td>Отчество<i class="red">*</i></td>
                            <td><form:input path="patronymic" class="required"/></td>
                        </tr>
                        <tr>
                            <td>№ карточки</td>
                            <td><form:input type="text" path="cardNumber"/></td>
                        </tr>
                        <tr>
                            <td>RMSys:</td>
                            <td>n/a</td>
                        </tr>
                    </table>
                </div>
                <div class="info_block">
                    <table>
                        <tr>
                            <td>Пол<i class="red">*</i></td>
                            <td>
                                <div style="width:110px" class="select_div">
                                    <form:select path="gender" id="gender"  cssClass="required">
                                        <form:option value=""/>
                                        <c:forEach items="${genders}" var="gender">
                                            <form:option value="${gender}"><spring:message code="${gender.value}"/></form:option>
                                        </c:forEach>
                                    </form:select>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>Дата рождения<i class="red">*</i></td>
                            <td><form:input id="card-birthday" path="birthday" class="date-picker required" /></td>
                        </tr>
                        <tr>
                            <td>Семейное положение</td>
                            <td>
                                <div class="select_div">
                                    <form:select path="familyStatus" id="familyStatus">
                                        <form:option value=""/>
                                        <c:forEach items="${familyStatuses}" var="familyStatus">
                                            <form:option value="${familyStatus}"><spring:message code="${familyStatus.value}"/></form:option>
                                        </c:forEach>
                                    </form:select>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>Статус</td>
                            <td>
                                <div class="select_div">
                                    <form:select path="status" id="status">
                                        <c:forEach items="${statuses}" var="status">
                                            <form:option value="${status}"><spring:message code="${status.value}"/></form:option>
                                        </c:forEach>
                                    </form:select>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <c:if test="${personCard.lastAssignment != null}">
                                    Должность: <spring:message code="${personCard.lastAssignment.position.value}"/>
                                </c:if>
                            </td>
                        </tr>
                    </table>
                </div>
                <c:choose>
                    <c:when test="${empty personCard.id}">
                        <div class="info_block third spacing">
                            <a id="export-personCard-excel" class="disabled-crud-icons" title="Экспорт в Excel"></a>
                            <i class="separator disabled-crud-icons">|</i>
                            <button id="parent-dialog-newDocument" data-person-id="0" class="button add_order disabled-crud-icons" disabled type="button">Добавить приказ</button>
                        </div>
                    </c:when>
                    <c:otherwise>
                        <div class="info_block third spacing">
                            <a id="export-personCard-excel" href="${pageContext.request.contextPath}/file/export/excel/T2/${personCard.id}" title="Экспорт в Excel"></a>
                            <i class="separator ${not empty personCard.id ? '' : 'disabled-crud-icons' }">|</i>
                            <button id="parent-dialog-newDocument" data-url="document" data-person-id="${personCard.id}" class="button add_order" type="button">Добавить приказ</button>
                        </div>
                    </c:otherwise>
                </c:choose>
                <div class="info_block third">
                    <table>
                        <tr>
                            <td>Таб №</td>
                            <td><form:input type="text" path="tabNumber"/></td>
                        </tr>
                        <tr>
                            <td>На испыт. сроке </td>
                            <td><form:checkbox path="testPeriod" id="test_period"/></td>
                        </tr>
                        <tr>
                            <td>Дата оконч. испыт. срока:</td>
                            <td><form:input path="testPeriodEndDate" class="date-picker" id="test_period_end_date"/></td>
                        </tr>
                    </table>
                </div>
            </div>
            <div id="dialog_tabs">
                <ul id="tabs-titles">
                    <li><a href="#generalInformation"><span>Общие сведения</span></a></li>
                    <li><a href="#familyInformation"><span>Состав семьи</span></a></li>
                    <li><a href="#educationInformation"><span>Образование</span></a></li>
                    <li><a href="#militaryInformation"><span>Воинский учет</span></a></li>
                    <li><a href="#vacationInformation"><span>Отпуска</span></a></li>
                    <li><a href="#documentInformation"><span>Документы</span></a></li>
                    <li><a href="#assignmentInformation"><span>Назначения/Перемещения</span></a></li>
                    <li><a href="#additionalInformation"><span>Дополнительные сведения</span></a></li>
                </ul>
                <div id="tabs-contents">
                    <div id="generalInformation">
                        <jsp:include page="general_information.jsp"/>
                    </div>
                    <div id="familyInformation">
                        <jsp:include page="family_information.jsp"/>
                    </div>
                    <div id="educationInformation">
                        <jsp:include page="education_information.jsp"/>
                    </div>
                    <div id="militaryInformation">
                        <jsp:include page="military_information.jsp"/>
                    </div>
                    <div id="vacationInformation">
                        <jsp:include page="vacation_information.jsp"/>
                    </div>
                    <div id="documentInformation">
                        <jsp:include page="documents_information.jsp"/>
                    </div>
                    <div id="assignmentInformation">
                        <jsp:include page="assignment_information.jsp"/>
                    </div>
                    <div id="additionalInformation">
                        <jsp:include page="additional_information.jsp"/>
                    </div>
                </div>
            </div>
        </form:form>
    </tiles:putAttribute>
</tiles:insertDefinition>

<div class="curtain">
    <div id="draggable">
        <div id="addNote" class="reveal-modal medium">
            <tiles:insertDefinition name="addNote">
                <tiles:putAttribute name="body">
                    <div id="noteContent"></div>
                </tiles:putAttribute>
            </tiles:insertDefinition>
        </div>
    </div>

</div>

PersonnelOffice/personneloffice-web/src/main/webapp/WEB-INF/pages/person/dialogs/documents_information.jsp
<%@ page import="com.coherent.api.dao.enums.documents.*" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<% pageContext.setAttribute("paperTypes", PaperTypeEnum.values()); %>


<div class="button-block ${not empty personCard.id ? '' : 'disabled-crud-icons' }">
    <!-- <a class="export-to-word" href="#"></a> -->
    <a class="add-row crud" href="#" data-url="document" data-person-id="${not empty personCard.id ? personCard.id : 0 }" data-id="0"></a>
    <!-- <a class="edit-row crud" href="#"></a> -->
    <a class="delete-row crud" href="#"></a>
</div>

<table class="orders-sort">
    <tr>
        <td><label for="doc-type-select" class="blue-label">Тип документа:</label></td>
        <td>
            <div id="doc-type-select" class="select_div">
                <select id="documentFilter">
                    <option value=""></option>
                        <c:forEach var="paperType" items="${paperTypes}">
                            <spring:message var="paperTypeLabel" code="${paperType.value}"/>
                        <option value="${paperType}">${paperTypeLabel}</option>
                    </c:forEach>
                </select>
            </div>
        </td>
    </tr>
</table>

<div class="info-tables-wrapper">

    <table id="documents_table" class="info-tables">
        <thead data-entity-attributes="data-id:id">
            <tr>
                <td data-entity-property="paperType">Тип Документа</td><!--  class="document-type"-->
                <td data-entity-property="paperNumber">№</td>
                <td data-entity-property="paperDate">Дата</td>
                <td data-entity-property="species">Вид</td>
                <td data-entity-property="reason">Основание</td>
            </tr>
        </thead>
        <tbody>
            <c:forEach items="${personCard.documents}" var="document">
                <tr data-url="document" data-person-id="${personCard.id}" data-id="${document.id}">
                    <td><%-- ${document.paperType} --%>
                        <c:if test="${document.paperType != null}">
                            <spring:message code="${document.paperType.value}"/>
                        </c:if>
                    </td><!--  class="document-type" -->
                    <td>
                        ${document.paperNumber}
                        <c:if test="${document.category != null }">
                            /
                            <spring:message code="${document.category.value}"/>
                        </c:if>
                    </td>
                    <td>
                        <spring:eval expression="document.paperDate"/>
                    </td>
                    <td>
                        <c:if test="${document.species != null }">
                            <spring:message code="${document.species.value}"/>
                        </c:if>
                        <c:if test="${document.subspecies != null }">
                            /
                            <spring:message code="${document.subspecies.value}"/>
                        </c:if>
                    </td>
                    <td>
                        ${document.reason}
                    </td>
                </tr>
            </c:forEach>
        </tbody>
    </table>

</div>

PersonnelOffice/personneloffice-web/src/main/webapp/WEB-INF/pages/person/dialogs/family_information.jsp
<%@ page import="com.coherent.api.dao.enums.family.*" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<% pageContext.setAttribute("familyMember", KinshipEnum.values()); %>


<div class="button-block ${not empty personCard.id ? '' : 'disabled-crud-icons' }">
    <a class="add-row crud" href="#" data-url="family_member" data-person-id="${not empty personCard.id ? personCard.id : 0 }" data-id="0"></a>
    <a class="edit-row crud" href="#"></a>
    <a class="delete-row crud" href="#"></a>
</div>
<table class="multi-child">
    <tr>
        <td class="blue-label">Многодетная семья:</td>
        <td><label for="large_family">№ удостоверения</label></td>
        <td><form:input id="large_family" path="largeFamily" /></td>
    </tr>
</table>

<hr>
<div class="info-tables-wrapper">

    <table id="family_table" class="info-tables">
        <thead data-entity-attributes="data-id:id">
            <tr>
                <td data-entity-property="kinship">Родство</td>
                <td data-entity-property="name">ФИО</td>
                <td data-entity-property="birthday">Дата Рождения</td>
                <td data-entity-property="invalid">Инвалид</td>
            </tr>
        </thead>
        <tbody>
        <c:forEach items="${personCard.familyMembers}" var="familyMember">
            <tr data-url="family_member" data-person-id="${personCard.id}" data-id="${familyMember.id}">
                <td>
                    <c:if test="${familyMember.kinship != null}">
                        <spring:message code="${familyMember.kinship.value}"/>
                    </c:if>
                </td>
                <td>${familyMember.name}</td>
                <td><spring:eval expression="familyMember.birthday"/></td>
                <td><c:if test="${familyMember.invalid}"><input id="invalid" type="checkbox" disabled checked></c:if></td>
            </tr>
        </c:forEach>
        </tbody>
    </table>

</div>